version: "3.8"
services:
  db:
    image: postgres:16
    container_name: skillsight_db
    environment:
      POSTGRES_USER: skillsight
      POSTGRES_PASSWORD: skillsight_pw
      POSTGRES_DB: skillsight
    ports:
      - "5432:5432"
    volumes:
      - skillsight_skillsight_pgdata:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: skillsight_redis
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: skillsight_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  skillsight_skillsight_pgdata:
    external: true
  qdrant_data:
