export const DEMO_DASHBOARD_DOCUMENTS = [
  { doc_id: 'demo-doc-1', filename: 'Demo_Resume.pdf', created_at: '2026-04-01T10:00:00Z', doc_type: 'resume' },
  { doc_id: 'demo-doc-2', filename: 'Demo_Data_Project.md', created_at: '2026-04-02T10:00:00Z', doc_type: 'project' },
];

export const DEMO_DASHBOARD_SKILLS = [
  {
    skill_id: 'HKU.SKILL.DATA_ANALYSIS.v1', canonical_name: 'Data Analysis', level: 2, status: 'verified' as const,
    frequency: 16,
    evidence_sources: [
      { chunk_id: 'dc-1', snippet: 'Performed exploratory data analysis on customer segmentation dataset', doc_id: 'demo-doc-2', filename: 'Demo_Data_Project.md' },
      { chunk_id: 'dc-2', snippet: 'Applied statistical analysis to identify key performance indicators', doc_id: 'demo-doc-2', filename: 'Demo_Data_Project.md' },
      { chunk_id: 'dc-3', snippet: 'Conducted data analysis for marketing campaign effectiveness', doc_id: 'demo-doc-1', filename: 'Demo_Resume.pdf' },
    ],
  },
  {
    skill_id: 'HKU.SKILL.SQL.v1', canonical_name: 'SQL', level: 2, status: 'verified' as const,
    frequency: 13,
    evidence_sources: [
      { chunk_id: 'dc-4', snippet: 'Wrote complex SQL queries to extract insights from relational databases', doc_id: 'demo-doc-2', filename: 'Demo_Data_Project.md' },
      { chunk_id: 'dc-5', snippet: 'Optimized SQL queries for large-scale data warehouse operations', doc_id: 'demo-doc-1', filename: 'Demo_Resume.pdf' },
    ],
  },
  {
    skill_id: 'HKU.SKILL.PYTHON.v1', canonical_name: 'Python', level: 2, status: 'verified' as const,
    frequency: 12,
    evidence_sources: [
      { chunk_id: 'dc-6', snippet: 'Built data pipeline using Python pandas and numpy libraries', doc_id: 'demo-doc-2', filename: 'Demo_Data_Project.md' },
      { chunk_id: 'dc-7', snippet: 'Developed Python scripts for automated report generation', doc_id: 'demo-doc-1', filename: 'Demo_Resume.pdf' },
    ],
  },
  {
    skill_id: 'HKU.SKILL.ML.v1', canonical_name: 'Machine Learning', level: 1, status: 'verified' as const,
    frequency: 5,
    evidence_sources: [
      { chunk_id: 'dc-8', snippet: 'Applied machine learning classification models on structured data', doc_id: 'demo-doc-2', filename: 'Demo_Data_Project.md' },
    ],
  },
  {
    skill_id: 'HKU.SKILL.STATISTICS.v1', canonical_name: 'Statistics', level: 1, status: 'verified' as const,
    frequency: 5,
    evidence_sources: [
      { chunk_id: 'dc-9', snippet: 'Performed hypothesis testing and regression analysis', doc_id: 'demo-doc-2', filename: 'Demo_Data_Project.md' },
    ],
  },
  {
    skill_id: 'HKU.SKILL.DATA_VIZ.v1', canonical_name: 'Data Visualization', level: 1, status: 'pending' as const,
    frequency: 3,
    evidence_sources: [
      { chunk_id: 'dc-10', snippet: 'Built dashboard for internship weekly metrics using Tableau', doc_id: 'demo-doc-1', filename: 'Demo_Resume.pdf' },
    ],
  },
  {
    skill_id: 'HKU.SKILL.COMMUNICATION.v1', canonical_name: 'Communication', level: 1, status: 'pending' as const,
    frequency: 3,
    evidence_sources: [
      { chunk_id: 'dc-11', snippet: 'Good presentation skills demonstrated in capstone project defense', doc_id: 'demo-doc-1', filename: 'Demo_Resume.pdf' },
      { chunk_id: 'dc-12', snippet: 'Engaged in group discussion activities for team project', doc_id: 'demo-doc-2', filename: 'Demo_Data_Project.md' },
    ],
  },
  {
    skill_id: 'HKU.SKILL.PRESENTATION.v1', canonical_name: 'Presentation', level: 0, status: 'missing' as const,
    frequency: 0,
    evidence_sources: [],
  },
  {
    skill_id: 'HKU.SKILL.DEEP_LEARNING.v1', canonical_name: 'Deep Learning', level: 0, status: 'missing' as const,
    frequency: 0,
    evidence_sources: [],
  },
];

export const DEMO_DASHBOARD_JOB_MATCHES = [
  {
    role_id: 'demo-role-1',
    role_title: 'Data Analyst — HSBC Hong Kong',
    readiness: 78,
    match_class: 'confirmed' as const,
    freshness_label: 'active' as const,
    freshness_age_days: 7,
    gaps: ['Excel', 'Storytelling'],
    gaps_all: ['Excel', 'Storytelling'],
    critical_gaps: ['Excel'],
    improvable_gaps: ['Storytelling'],
    required_skills: ['Data Analysis', 'SQL', 'Data Visualization', 'Statistics', 'Communication', 'Excel', 'Storytelling'],
    required_skills_all: ['Data Analysis', 'SQL', 'Data Visualization', 'Statistics', 'Communication', 'Excel', 'Storytelling'],
    required_skills_must: ['Data Analysis', 'SQL', 'Statistics', 'Excel'],
    required_skills_optional: ['Data Visualization', 'Communication', 'Storytelling'],
    skills_met: 5,
    skills_total: 7,
    skills_met_must: 3,
    skills_total_must: 4,
    skills_met_optional: 2,
    skills_total_optional: 3,
    match_ratio_must: 0.75,
    next_best_assessment: { skill_id: 'HKU.SKILL.EXCEL.v1', skill_name: 'Excel', reason: 'critical_gap' },
  },
  {
    role_id: 'demo-role-2',
    role_title: 'Product Analyst — Meituan (Beijing)',
    readiness: 72,
    match_class: 'confirmed' as const,
    freshness_label: 'active' as const,
    freshness_age_days: 3,
    gaps: ['Experiment Design', 'Storytelling'],
    gaps_all: ['Experiment Design', 'Storytelling'],
    critical_gaps: ['Experiment Design'],
    improvable_gaps: ['Storytelling'],
    required_skills: ['Data Analysis', 'SQL', 'Communication', 'Experiment Design', 'Storytelling'],
    required_skills_all: ['Data Analysis', 'SQL', 'Communication', 'Experiment Design', 'Storytelling'],
    required_skills_must: ['Data Analysis', 'SQL', 'Experiment Design'],
    required_skills_optional: ['Communication', 'Storytelling'],
    skills_met: 3,
    skills_total: 5,
    skills_met_must: 2,
    skills_total_must: 3,
    skills_met_optional: 1,
    skills_total_optional: 2,
    match_ratio_must: 0.6667,
    next_best_assessment: { skill_id: 'HKU.SKILL.EXPERIMENT_DESIGN.v1', skill_name: 'Experiment Design', reason: 'critical_gap' },
  },
  {
    role_id: 'demo-role-3',
    role_title: 'BI Analyst — WeLab',
    readiness: 69,
    match_class: 'confirmed' as const,
    freshness_label: 'recent' as const,
    freshness_age_days: 18,
    gaps: ['Dashboarding'],
    gaps_all: ['Dashboarding'],
    critical_gaps: [],
    improvable_gaps: ['Dashboarding'],
    required_skills: ['Data Analysis', 'SQL', 'Data Visualization', 'Dashboarding'],
    required_skills_all: ['Data Analysis', 'SQL', 'Data Visualization', 'Dashboarding'],
    required_skills_must: ['SQL', 'Data Visualization'],
    required_skills_optional: ['Data Analysis', 'Dashboarding'],
    skills_met: 3,
    skills_total: 4,
    skills_met_must: 2,
    skills_total_must: 2,
    skills_met_optional: 1,
    skills_total_optional: 2,
    match_ratio_must: 1.0,
    next_best_assessment: { skill_id: 'HKU.SKILL.DASHBOARDING.v1', skill_name: 'Dashboarding', reason: 'improvable_gap' },
  },
  {
    role_id: 'demo-role-4',
    role_title: 'ML Engineer — ByteDance (Shanghai)',
    readiness: 67,
    match_class: 'potential' as const,
    freshness_label: 'active' as const,
    freshness_age_days: 5,
    gaps: ['Deep Learning', 'MLOps'],
    gaps_all: ['Deep Learning', 'MLOps'],
    critical_gaps: ['Deep Learning'],
    improvable_gaps: ['MLOps'],
    required_skills: ['Python', 'Machine Learning', 'Statistics', 'Deep Learning', 'MLOps'],
    required_skills_all: ['Python', 'Machine Learning', 'Statistics', 'Deep Learning', 'MLOps'],
    required_skills_must: ['Python', 'Machine Learning', 'Deep Learning'],
    required_skills_optional: ['Statistics', 'MLOps'],
    skills_met: 3,
    skills_total: 5,
    skills_met_must: 2,
    skills_total_must: 3,
    skills_met_optional: 1,
    skills_total_optional: 2,
    match_ratio_must: 0.6667,
    next_best_assessment: { skill_id: 'HKU.SKILL.DEEP_LEARNING.v1', skill_name: 'Deep Learning', reason: 'critical_gap' },
  },
  {
    role_id: 'demo-role-5',
    role_title: 'AI Product Specialist — Alibaba Cloud',
    readiness: 64,
    match_class: 'potential' as const,
    freshness_label: 'recent' as const,
    freshness_age_days: 25,
    gaps: ['Product Sense'],
    gaps_all: ['Product Sense'],
    critical_gaps: ['Product Sense'],
    improvable_gaps: [],
    required_skills: ['Machine Learning', 'Communication', 'Data Analysis', 'Product Sense'],
    required_skills_all: ['Machine Learning', 'Communication', 'Data Analysis', 'Product Sense'],
    required_skills_must: ['Machine Learning', 'Data Analysis', 'Product Sense'],
    required_skills_optional: ['Communication'],
    skills_met: 3,
    skills_total: 4,
    skills_met_must: 2,
    skills_total_must: 3,
    skills_met_optional: 1,
    skills_total_optional: 1,
    match_ratio_must: 0.6667,
    next_best_assessment: { skill_id: 'HKU.SKILL.PRODUCT_SENSE.v1', skill_name: 'Product Sense', reason: 'critical_gap' },
  },
  {
    role_id: 'demo-role-6',
    role_title: 'Data Scientist — Deloitte HK',
    readiness: 58,
    match_class: 'potential' as const,
    freshness_label: 'recent' as const,
    freshness_age_days: 40,
    gaps: ['Deep Learning', 'Feature Engineering', 'Model Deployment'],
    gaps_all: ['Deep Learning', 'Feature Engineering', 'Model Deployment'],
    critical_gaps: ['Deep Learning', 'Feature Engineering'],
    improvable_gaps: ['Model Deployment'],
    required_skills: ['Python', 'Machine Learning', 'Deep Learning', 'Feature Engineering', 'Model Deployment'],
    required_skills_all: ['Python', 'Machine Learning', 'Deep Learning', 'Feature Engineering', 'Model Deployment'],
    required_skills_must: ['Python', 'Machine Learning', 'Deep Learning', 'Feature Engineering'],
    required_skills_optional: ['Model Deployment'],
    skills_met: 2,
    skills_total: 5,
    skills_met_must: 2,
    skills_total_must: 4,
    skills_met_optional: 0,
    skills_total_optional: 1,
    match_ratio_must: 0.5,
    next_best_assessment: { skill_id: 'HKU.SKILL.DEEP_LEARNING.v1', skill_name: 'Deep Learning', reason: 'critical_gap' },
  },
  {
    role_id: 'demo-role-7',
    role_title: 'Quant Analyst — HKEX',
    readiness: 55,
    match_class: 'potential' as const,
    freshness_label: 'aging' as const,
    freshness_age_days: 90,
    gaps: ['Linear Algebra', 'Risk Modeling'],
    gaps_all: ['Linear Algebra', 'Risk Modeling'],
    critical_gaps: ['Linear Algebra'],
    improvable_gaps: ['Risk Modeling'],
    required_skills: ['Statistics', 'Python', 'Linear Algebra', 'Risk Modeling'],
    required_skills_all: ['Statistics', 'Python', 'Linear Algebra', 'Risk Modeling'],
    required_skills_must: ['Statistics', 'Python', 'Linear Algebra'],
    required_skills_optional: ['Risk Modeling'],
    skills_met: 2,
    skills_total: 4,
    skills_met_must: 2,
    skills_total_must: 3,
    skills_met_optional: 0,
    skills_total_optional: 1,
    match_ratio_must: 0.6667,
    next_best_assessment: { skill_id: 'HKU.SKILL.LINEAR_ALGEBRA.v1', skill_name: 'Linear Algebra', reason: 'critical_gap' },
  },
  {
    role_id: 'demo-role-8',
    role_title: 'NLP Engineer — Tencent (Shenzhen)',
    readiness: 53,
    match_class: 'potential' as const,
    freshness_label: 'active' as const,
    freshness_age_days: 10,
    gaps: ['NLP', 'Transformers', 'Prompt Engineering'],
    gaps_all: ['NLP', 'Transformers', 'Prompt Engineering'],
    critical_gaps: ['NLP', 'Transformers'],
    improvable_gaps: ['Prompt Engineering'],
    required_skills: ['Python', 'Machine Learning', 'NLP', 'Transformers', 'Prompt Engineering'],
    required_skills_all: ['Python', 'Machine Learning', 'NLP', 'Transformers', 'Prompt Engineering'],
    required_skills_must: ['Python', 'Machine Learning', 'NLP', 'Transformers'],
    required_skills_optional: ['Prompt Engineering'],
    skills_met: 2,
    skills_total: 5,
    skills_met_must: 2,
    skills_total_must: 4,
    skills_met_optional: 0,
    skills_total_optional: 1,
    match_ratio_must: 0.5,
    next_best_assessment: { skill_id: 'HKU.SKILL.NLP.v1', skill_name: 'NLP', reason: 'critical_gap' },
  },
];

export const DEMO_SKILLS_PROFILE = {
  subject_id: 'demo_student',
  documents_count: 2,
  documents: [
    { doc_id: 'demo-doc-1', filename: 'Demo_Resume.pdf', status: 'completed', scope: 'private' },
    { doc_id: 'demo-doc-2', filename: 'Demo_Data_Project.md', status: 'completed', scope: 'private' },
  ],
  generated_at: '2026-04-07T10:00:00Z',
  skills: [
    {
      skill_id: 'HKU.SKILL.DATA_ANALYSIS.v1',
      canonical_name: 'Data Analysis',
      label: 'demonstrated',
      rationale: 'Demonstrated via coursework and project report.',
      evidence_items: [{ chunk_id: 'demo-chunk-1', snippet: 'Performed exploratory analysis and interpreted trends.', doc_id: 'demo-doc-2' }],
    },
    {
      skill_id: 'HKU.SKILL.DATA_VIZ.v1',
      canonical_name: 'Data Visualization',
      label: 'mentioned',
      rationale: 'Mentioned in resume but lacks strong artifacts.',
      evidence_items: [{ chunk_id: 'demo-chunk-2', snippet: 'Built dashboard for internship weekly metrics.', doc_id: 'demo-doc-1' }],
    },
    {
      skill_id: 'HKU.SKILL.DEEP_LEARNING.v1',
      canonical_name: 'Deep Learning',
      label: 'not_enough_information',
      rationale: 'No concrete evidence found in uploaded documents.',
      evidence_items: [],
      refusal: {
        code: 'not_enough_information',
        message: 'More concrete project proof is needed.',
        next_step: 'Upload model training project or coursework artifacts.',
      },
    },
  ],
};

export const DEMO_RECENT_ASSESSMENT_UPDATES = [
  {
    session_id: 'demo-session-1',
    assessment_type: 'communication',
    skill_id: 'HKU.SKILL.COMMUNICATION.v1',
    score: 82,
    level: 2,
    submitted_at: '2026-04-05T08:00:00Z',
    skill_update: { level: 2, label: 'demonstrated', updated_at: '2026-04-05T08:01:00Z' },
  },
  {
    session_id: 'demo-session-2',
    assessment_type: 'programming',
    skill_id: 'HKU.SKILL.PYTHON.v1',
    score: 76,
    level: 2,
    submitted_at: '2026-04-06T08:00:00Z',
    skill_update: { level: 2, label: 'mentioned', updated_at: '2026-04-06T08:01:00Z' },
  },
];

export const DEMO_PEER_BENCHMARK = [
  { skill_id: 'Data Analysis', level: 2, percentile: 68 },
  { skill_id: 'SQL', level: 2, percentile: 72 },
  { skill_id: 'Python Programming', level: 1, percentile: 45 },
  { skill_id: 'Data Visualization', level: 1, percentile: 38 },
  { skill_id: 'Statistical Analysis', level: 2, percentile: 61 },
  { skill_id: 'Machine Learning', level: 0, percentile: 22 },
  { skill_id: 'Project Management', level: 1, percentile: 50 },
  { skill_id: 'Communication', level: 2, percentile: 75 },
];

export const DEMO_JOBS_LIVE = [
  // Hong Kong listings
  { posting_id: 'demo-job-1', source_site: 'jobsdb_hk', title: 'Data Analyst', company: 'HSBC', location: 'Hong Kong', salary: 'HKD 28,000 – 38,000/month', source_url: 'https://hk.jobsdb.com/', match_score: 72, matched_skills: ['Data Analysis', 'SQL'] },
  { posting_id: 'demo-job-2', source_site: 'jobsdb_hk', title: 'Business Analyst', company: 'Deloitte HK', location: 'Hong Kong', salary: 'HKD 32,000 – 45,000/month', source_url: 'https://hk.jobsdb.com/', match_score: 65, matched_skills: ['Data Analysis'] },
  { posting_id: 'demo-job-3', source_site: 'ctgoodjobs_hk', title: 'Data Scientist', company: 'WeLab', location: 'Hong Kong', salary: 'HKD 40,000 – 60,000/month', source_url: 'https://www.ctgoodjobs.hk/', match_score: 55, matched_skills: ['Python', 'Machine Learning'] },
  { posting_id: 'demo-job-4', source_site: 'ctgoodjobs_hk', title: 'BI Developer', company: 'HKEX', location: 'Hong Kong', salary: 'HKD 35,000 – 50,000/month', source_url: 'https://www.ctgoodjobs.hk/', match_score: 48, matched_skills: ['SQL', 'Data Visualization'] },
  // Mainland China — Boss直聘 real search links (clicking opens live Boss直聘 results)
  { posting_id: 'demo-job-5', source_site: 'boss_zhipin', title: '数据分析师（用户增长方向）', company: '美团', location: '北京·朝阳区', salary: '20K–35K/月', source_url: 'https://www.zhipin.com/web/geek/job?query=%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90%E5%B8%88&city=101010100', match_score: 70, matched_skills: ['Data Analysis', 'SQL', 'Python'] },
  { posting_id: 'demo-job-6', source_site: 'boss_zhipin', title: '推荐算法工程师（校招）', company: '字节跳动', location: '上海·浦东新区', salary: '35K–60K/月', source_url: 'https://www.zhipin.com/web/geek/job?query=%E7%AE%97%E6%B3%95%E5%B7%A5%E7%A8%8B%E5%B8%88&city=101020100', match_score: 62, matched_skills: ['Machine Learning', 'Python', 'Statistics'] },
  { posting_id: 'demo-job-7', source_site: 'boss_zhipin', title: '产品数据分析师（实习）', company: '腾讯', location: '深圳·南山区', salary: '300–400元/天', source_url: 'https://www.zhipin.com/web/geek/job?query=%E4%BA%A7%E5%93%81%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90&city=101280600', match_score: 68, matched_skills: ['Data Analysis', 'SQL', 'Communication'] },
  { posting_id: 'demo-job-8', source_site: 'boss_zhipin', title: 'NLP 算法研究员（实习）', company: '阿里巴巴达摩院', location: '杭州·余杭区', salary: '300–500元/天', source_url: 'https://www.zhipin.com/web/geek/job?query=NLP%E5%B7%A5%E7%A8%8B%E5%B8%88&city=101210100', match_score: 45, matched_skills: ['Python', 'Machine Learning'] },
  { posting_id: 'demo-job-9', source_site: 'boss_zhipin', title: '商业智能分析师 BI', company: '京东科技', location: '北京·亦庄开发区', salary: '18K–30K/月', source_url: 'https://www.zhipin.com/web/geek/job?query=%E5%95%86%E4%B8%9A%E6%99%BA%E8%83%BD%E5%88%86%E6%9E%90%E5%B8%88&city=101010100', match_score: 55, matched_skills: ['SQL', 'Data Visualization', 'Data Analysis'] },
  { posting_id: 'demo-job-10', source_site: 'boss_zhipin', title: '数据科学家（金融科技方向）', company: '平安科技', location: '深圳·福田区', salary: '30K–50K/月', source_url: 'https://www.zhipin.com/web/geek/job?query=%E6%95%B0%E6%8D%AE%E7%A7%91%E5%AD%A6%E5%AE%B6&city=101280600', match_score: 58, matched_skills: ['Python', 'Statistics', 'Machine Learning'] },
  { posting_id: 'demo-job-11', source_site: 'boss_zhipin', title: '量化研究员（校招）', company: '招商证券', location: '上海·黄浦区', salary: '25K–45K/月', source_url: 'https://www.zhipin.com/web/geek/job?query=%E9%87%8F%E5%8C%96%E7%A0%94%E7%A9%B6%E5%91%98&city=101020100', match_score: 42, matched_skills: ['Statistics', 'Python'] },
  { posting_id: 'demo-job-12', source_site: 'boss_zhipin', title: '机器学习工程师（华为云）', company: '华为云', location: '成都·高新区', salary: '25K–45K/月', source_url: 'https://www.zhipin.com/web/geek/job?query=%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E5%B7%A5%E7%A8%8B%E5%B8%88&city=101270100', match_score: 52, matched_skills: ['Python', 'Machine Learning'] },
];
