"""Build exportable attribution report documents (DOCX)."""
from __future__ import annotations

from io import BytesIO
from typing import Any, Dict, List, Optional

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt


def _safe_text(v: Any) -> str:
    if v is None:
        return ""
    return str(v)


def _dict_to_score_rows(scores: Any) -> List[Dict[str, Any]]:
    if not isinstance(scores, dict):
        return []
    rows: List[Dict[str, Any]] = []
    for k, v in scores.items():
        if isinstance(v, dict):
            rows.append(
                {
                    "dimension": k,
                    "score": v.get("score"),
                    "comment": _safe_text(v.get("comment")),
                }
            )
    return rows


def build_attribution_report_docx(
    *,
    review_id: str,
    target_role_id: Optional[str],
    total_initial: Optional[float],
    total_final: Optional[float],
    initial_scores: Any,
    final_scores: Any,
    verification_snapshot: Any,
    attribution: Dict[str, Any],
) -> bytes:
    """Create a report DOCX with explainable scoring attribution and verification."""
    doc = Document()
    title = doc.add_paragraph("SkillSight Resume Explainability Report")
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if title.runs:
        title.runs[0].font.size = Pt(18)
        title.runs[0].bold = True

    meta = doc.add_paragraph()
    meta.add_run(f"Review ID: {_safe_text(review_id)}\n").bold = True
    meta.add_run(f"Target Role: {_safe_text(target_role_id or '-')}\n")
    meta.add_run(f"Initial Total: {_safe_text(total_initial)}\n")
    meta.add_run(f"Final Total: {_safe_text(total_final)}\n")

    doc.add_heading("Score Attribution", level=2)
    attr = attribution or {}
    by_dim = attr.get("by_dimension") if isinstance(attr, dict) else []
    if isinstance(by_dim, list) and by_dim:
        tbl = doc.add_table(rows=1, cols=6)
        hdr = tbl.rows[0].cells
        hdr[0].text = "Dimension"
        hdr[1].text = "Before"
        hdr[2].text = "After"
        hdr[3].text = "Delta"
        hdr[4].text = "Signal"
        hdr[5].text = "Alignment"
        for row in by_dim:
            r = tbl.add_row().cells
            r[0].text = _safe_text(row.get("dimension"))
            r[1].text = _safe_text(row.get("score_before"))
            r[2].text = _safe_text(row.get("score_after"))
            r[3].text = _safe_text(row.get("score_delta"))
            r[4].text = _safe_text(row.get("change_signal"))
            r[5].text = _safe_text(row.get("alignment"))
    else:
        doc.add_paragraph("No attribution rows available.")
    doc.add_paragraph(f"Total Delta: {_safe_text(attr.get('total_delta') if isinstance(attr, dict) else None)}")

    doc.add_heading("Dimension Comments", level=2)
    final_rows = _dict_to_score_rows(final_scores)
    if final_rows:
        for row in final_rows:
            p = doc.add_paragraph(style=None)
            p.add_run(f"{row['dimension']}: ").bold = True
            p.add_run(f"Score {_safe_text(row['score'])} — {_safe_text(row['comment'])}")
    else:
        doc.add_paragraph("No final score comments available.")

    doc.add_heading("Verification Snapshot", level=2)
    if isinstance(verification_snapshot, dict):
        summary = verification_snapshot.get("summary") if isinstance(verification_snapshot.get("summary"), dict) else {}
        doc.add_paragraph(
            f"Verdict: {_safe_text(summary.get('verdict'))}, "
            f"Coverage: {_safe_text(summary.get('coverage'))}, "
            f"Confidence: {_safe_text(summary.get('confidence'))}"
        )
        claims = verification_snapshot.get("claims") if isinstance(verification_snapshot.get("claims"), list) else []
        for c in claims[:12]:
            cp = doc.add_paragraph(style=None)
            cp.add_run(f"- {_safe_text(c.get('text'))}\n").bold = True
            cp.add_run(
                f"  verdict={_safe_text(c.get('verdict'))}, "
                f"confidence={_safe_text(c.get('confidence'))}, "
                f"refs={_safe_text(c.get('evidence_refs'))}"
            )
        issues = verification_snapshot.get("issues") if isinstance(verification_snapshot.get("issues"), list) else []
        if issues:
            doc.add_paragraph("Verification Issues:")
            for it in issues[:15]:
                doc.add_paragraph(f"- [{_safe_text(it.get('level'))}] {_safe_text(it.get('message'))}")
    else:
        doc.add_paragraph("No verification snapshot available.")

    doc.add_heading("Notes", level=2)
    doc.add_paragraph(
        "This report is generated by heuristic and AI-assisted scoring logic. "
        "Please review details before external use."
    )

    out = BytesIO()
    doc.save(out)
    out.seek(0)
    return out.read()

